language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - export $PWD="$(pwd)"
  - python -m unittest discover -s $PWD/tests -t $PWD/left-court/tests in $PWD/left-court/tests